---
title: "Lab2_McSweeney"
author: "Danny McSweeney"
date: "1/29/2020"
output: html_document
---

```{r}
SNPs <- c("AA", "AA", "GG", "AG", "AG", "AA", "AG", "AA", "AA", "AA", "AG")
SNPs
```

```{r}
SNPs_cat <- factor(SNPs)
SNPs_cat
```

```{r}
table(SNPs_cat)
plot(SNPs_cat)
```

```{r}
as.numeric(SNPs_cat)
```

```{r}
Day1 <- c(2,4,6,8)
Day2 <- c(3,6,9,12)
Day3 <- c(1,4,9,16)
A <- cbind(Day1, Day2,Day3)
A
A<- rbind(Day1,Day2,Day3)
A
A <- cbind(Day1, Day2,Day3)
A
B <- rbind(Day1,Day2,Day3)
B
```

```{r}
Day4 <- c(5,10,11,20)
C <- rbind(B,Day4)
C
```

```{r}
Day4 <- c(5,10,11,20)
C <- rbind(B,Day4)
C
```

```{r}
A*10

A[1]
A[12]

A[ ,c(1,3)]
A[c(2,4), ]

A
t(A)
```

```{r}
Gene1 <- c(2,4,6,8)
Gene2 <- c(3,6,9,12)
Gene3 <- c(1,4,9,16)
Gene <- c("Day 1", "Day 2", "Day 3", "Day 4")
```

```{r}
RNAseq <- data.frame(Gene1, Gene2, Gene3, row.names = Gene)
RNAseq
```

```{r}
RNAseq$Gene3
plot(RNAseq$Gene1, RNAseq$Gene3)
```

```{r}
plot(RNAseq$Day,RNAseq$Gene3)
```

```{r}
RNAseq$Gene4 <- c(5,10,15,20)
RNAseq
```

```{r}
RNAseq$Gene5 <- c(1,2,3,3)
```

```{r}
RNAseq["Day 4",] <- rbind(10,14,20,22,3)
```

```{r}
x=1
str(x)
a="ATGCCCTGA"
a
```

```{r}
str(SNPs)
SNPs <- c("AA", "AA", "GG", "AG", "AG", "AA", "AG", "AA", "AA", "AA", "AG")
str(SNPs_cat)
```

```{r}
B <- rbind(Day1,Day2,Day3)
str (B)
```

```{r}
Gene1
Gene2
Gene3
Gene
RNAseq<- data.frame(Gene1,Gene2,Gene3, row.names = Gene)
str (RNAseq)
```















