---
title: "lab3"
author: "Danny McSweeney"
date: "3/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
SNPs <- read.table("23andME_complete.txt", header = TRUE, sep = "\t")
```

```{r}
str(SNPs)
```

```{r}
class(SNPs)
```

```{r}
typeof(SNPs)
```

```{r}
str(SNPs)
```


```{r}
summary(SNPs)
```

```{r}
class(SNPs$genotype)
```


```{r}
typeof(SNPs$genotype)
```


```{r}
str(SNPs$genotype)
```


```{r}
summary(SNPs$genotype)
```

```{r}
summary(SNPs$chromosome)
```


```{r}
summary(SNPs$position)
```


```{r}
summary(SNPs$chromosome)
```


```{r}
SNPs$chromosome = ordered(SNPs$chromosome, levels=c(seq(1, 22), "X", "Y", "MT"))
summary(SNPs$chromosome)
```

```{r}
#Exercise No 1
plot(SNPs$chromosome)
```


```{r}
#Exercise No. 2
SNPs$chromosome = ordered(SNPs$chromosome, levels=c(seq(1, 22), "X", "Y", "MT"))
summary(SNPs$chromosome)
```


```{r}
plot(ordered(SNPs$chromosome, levels=c(seq(1, 22), "X", "Y", "MT")))
```
```{r}
#Exercise No. 3
ggplot(SNPs, aes(chromosome, fill=genotype)) + geom_bar(color="black")
```


```{r}
#Exercise No. 4
ggplot(SNPs, aes(chromosome, fill=genotype)) + geom_bar(position="fill")
```
```{r}
#Exercise No. 5
ggplot(SNPs, aes(chromosome, fill=genotype)) + geom_bar(position="dodge")
```


```{r}
#Exercise No. 6
ggplot(SNPs, aes(chromosome, fill=genotype)) + geom_bar(position="dodge") + facet_wrap(~chromosome)
```

